server:
  port: 8080
  servlet:
    session:
      cookie:
        name: UISESSIONCOUPON

spring:
  profiles:
    # withoutCORS , defaultCORS ,simpleCORS
    active: simpleCORS

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    import org.springframework.cloud.netflix.zuul: DEBUG

